import type { Resume } from "./schema";

export const resume = {
  basics: {
    name: "Thomas Berrios",
    label: "Full Stack Developer",
    description:
      "Full stack developer working across TypeScript applications, backend systems, DevOps, and open-source Linux tooling.",
    availability: "Looking for work",
    email: "thomas@thomasberrios.com",
    profiles: [
      {
        label: "LinkedIn",
        url: "https://linkedin.com/in/thomas-berrios",
      },
      {
        label: "GitHub",
        url: "https://github.com/TB516",
      },
    ],
  },
  education: [
    {
      institution: "Rochester Institute of Technology",
      area: "Game Design & Development",
      studyType: "BS",
      period: { start: "2022-08", end: "2025-12" },
      honors: ["summa cum laude"],
      minors: ["Software Engineering", "History"],
    },
  ],
  skills: [
    {
      name: "Programming Languages",
      keywords: ["JavaScript", "TypeScript", "Node.js", "C#", "Python", "Java", "C++"],
    },
    {
      name: "Frameworks",
      keywords: [
        "React",
        "Next",
        "Svelte",
        "SvelteKit",
        "Express",
        "Electron",
        "Jest",
        "Vitest",
        "Playwright",
        "ASP.NET",
        "Spring Boot",
      ],
    },
    {
      name: "Database",
      keywords: ["SQL", "PostgreSQL", "MySQL", "MongoDB", "Redis"],
    },
    {
      name: "DevOps",
      keywords: [
        "Docker",
        "Containerization",
        "AWS",
        "Cloud Computing",
        "CI/CD",
        "GitHub Actions",
        "Linux (Ubuntu, RHEL, Fedora)",
      ],
    },
    {
      name: "Agentic Development",
      keywords: ["OpenAI Codex", "Claude Code", "T3 Code"],
    },
  ],
  work: [
    {
      name: "iD Tech",
      roles: ["Lead Instructor – Teen Academy"],
      period: { start: "2026-07", end: "2026-08" },
      location: "New York, NY",
      summary: "Led project-based courses in Unreal Engine 5, Python, AI, and agentic development",
      highlights: [
        "Led project-based instruction in Unreal Engine 5 and Python, teaching core programming, game design, software engineering, and debugging concepts",
        "Guided students through hands-on projects incorporating AI and agentic development workflows, helping them turn course concepts into working software and game prototypes",
        "Collaborated with camp leadership on daily operations, student supervision, and activities, maintaining a safe and engaging learning environment",
      ],
      keywords: [
        "Unreal Engine 5",
        "Python",
        "AI",
        "Agentic Development",
        "Game Design",
        "Software Engineering",
        "Debugging",
      ],
    },
    {
      name: "Rochester Institute of Technology",
      roles: ["Teaching Assistant"],
      period: { start: "2024-08", end: "2025-12" },
      location: "Rochester, NY",
      summary:
        "Evaluated C# assignments and supported students with debugging and project implementation",
      highlights: [
        "Evaluated and provided feedback on C# assignments covering data structures, algorithms, object-oriented programming, and GUI development",
        "Assisted students with debugging and project implementation using C#, Windows Forms, and MonoGame",
        "Supported course delivery across three semesters, reinforcing core software engineering concepts",
      ],
      keywords: [
        "C#",
        "Windows Forms",
        "MonoGame",
        "Data Structures",
        "Algorithms",
        "Object-Oriented Programming",
        "GUI Development",
        "Debugging",
      ],
    },
    {
      name: "RIT School of Interactive Games and Media",
      roles: ["Backend Developer", "DevOps Lead"],
      period: { start: "2025-05", end: "2025-08" },
      summary: "Led a TypeScript backend rewrite and DevOps work for a 20-person team",
      highlights: [
        "Led backend and DevOps efforts on a 20-person team, leading a full backend rewrite of a legacy Express/MySQL codebase into a modular architecture using Prisma, service/controller layers, and TypeScript",
        "Containerized development and production environments using Docker Compose and Podman, eliminating manual database setup and improving onboarding with reproducible environments",
        "Managed and configured production infrastructure including Apache HTTPD reverse proxy, Shibboleth SSO integration, and S3 storage",
      ],
      keywords: [
        "TypeScript",
        "Express",
        "MySQL",
        "Prisma",
        "Docker Compose",
        "Podman",
        "Apache HTTPD",
        "Shibboleth",
        "Amazon S3",
      ],
    },
    {
      name: "iD Tech",
      roles: ["Lead Instructor – Teen Academy"],
      period: { start: "2024-07", end: "2024-08" },
      location: "New York, NY",
      summary: "Led project-based C++ and Unreal Engine instruction for the Teen Academy program",
      highlights: [
        "Led project-based instruction in C++ and Unreal Engine, teaching core software engineering, gameplay programming, and game development concepts",
        "Guided students through hands-on game projects from initial design and implementation through debugging and final presentation",
        "Assisted the director with daily camp operations, student supervision, and the planning of activities and off-site trips",
      ],
      keywords: [
        "C++",
        "Unreal Engine",
        "Gameplay Programming",
        "Game Development",
        "Software Engineering",
        "Debugging",
      ],
    },
    {
      name: "iD Tech",
      roles: ["Lead Instructor – Tech Camp"],
      period: { start: "2024-06", end: "2024-07" },
      location: "New York, NY",
      summary: "Led project-based courses spanning Unreal Engine, Unity VR, C#, C++, and Python",
      highlights: [
        "Led instruction in Unreal Engine, Unity VR, C#, C++, and Python fundamentals, teaching students core software engineering and game development concepts",
        "Delivered hands-on projects integrating graphics programming with SFML and Box2D, 3D asset creation, API-driven features, and introductory machine learning workflows",
        "Worked with the director to coordinate daily operations, supervise students, and support camp activities and events",
      ],
      keywords: [
        "Unreal Engine",
        "Unity VR",
        "C#",
        "C++",
        "Python",
        "SFML",
        "Box2D",
        "Machine Learning",
      ],
    },
  ],
  projects: [
    {
      name: "Bootc Buddy",
      roles: ["Lead Developer"],
      period: { start: "2026-06", end: "present" },
      summary: "Building a Flatpak-first bootc management app with React, TypeScript, and GTKX",
      highlights: [
        "Building a Flatpak-first bootc management app with React, TypeScript, and GTKX",
        "Built a reproducible GNOME Flatpak build and bundling pipeline with Node.js, pnpm, Vite hot module replacement, and automated scripts",
        "Developing Flatpak-friendly IPC using Unix Domain Sockets",
      ],
      keywords: [
        "React",
        "TypeScript",
        "GTKX",
        "Flatpak",
        "GNOME",
        "Node.js",
        "pnpm",
        "Vite",
        "Unix Domain Sockets",
      ],
      links: [
        {
          label: "GitHub",
          url: "https://github.com/TB516/bootc-buddy",
        },
      ],
    },
    {
      name: "r2modman",
      roles: ["Open-source Contributor"],
      period: { start: "2026-02", end: "present" },
      summary: "Contributing upstream Linux and Flatpak fixes to r2modmanPlus",
      highlights: [
        "Contributed upstream Linux/Flatpak fixes to r2modmanPlus, implementing portal-based Steam launching with xdg-open, Flatpak Steam permissions, and Steam Deck game-mode fallbacks",
        "Prepared a Flathub-compatible Flatpak distribution with AppStream metadata, desktop integration, sandbox configuration, CI builds, and a signed Cloudflare R2 repository pipeline for automatic updates",
        "Continuing to triage Linux and Flatpak issues, test changes across Steam environments, and submit upstream fixes as the project evolves",
      ],
      keywords: [
        "Linux",
        "Flatpak",
        "Flathub",
        "Steam",
        "Steam Deck",
        "xdg-open",
        "AppStream",
        "CI",
        "Cloudflare R2",
      ],
      links: [
        {
          label: "Homepage",
          url: "https://thunderstore.io/c/riskofrain2/p/ebkr/r2modman/",
        },
        {
          label: "Upstream repository",
          url: "https://github.com/ebkr/r2modmanPlus",
        },
      ],
    },
  ],
} satisfies Resume;
